// Code generated by protoc-gen-go.
// source: golang.conradwood.net/apis/pinger/pinger.proto
// DO NOT EDIT!

/*
Package pinger is a generated protocol buffer package.

It is generated from these files:
	golang.conradwood.net/apis/pinger/pinger.proto

It has these top-level messages:
	PingResult
	PingRequest
	PingListRequest
	PingList
	PingEntry
	PingTargetStatus
	PingTargetStatusList
	SetPingStatusRequest
	PingStatus
	PingStatusList
	Tag
	IP
	Host
	Route
	AddTagRequest
	RemoveTagRequest
	TagList
	AddIPRequest
	StatusMatrixList
	StatusMatrix
	MatrixColumnHeading
	MatrixRow
	MatrixEntry
*/
package pinger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "golang.conradwood.net/apis/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// result of a single ping
type PingResult struct {
	IP           string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	Milliseconds uint32 `protobuf:"varint,2,opt,name=Milliseconds" json:"Milliseconds,omitempty"`
	Success      bool   `protobuf:"varint,3,opt,name=Success" json:"Success,omitempty"`
}

func (m *PingResult) Reset()                    { *m = PingResult{} }
func (m *PingResult) String() string            { return proto.CompactTextString(m) }
func (*PingResult) ProtoMessage()               {}
func (*PingResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingResult) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *PingResult) GetMilliseconds() uint32 {
	if m != nil {
		return m.Milliseconds
	}
	return 0
}

func (m *PingResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// ping something once
type PingRequest struct {
	IP string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type PingListRequest struct {
	PingerID string `protobuf:"bytes,1,opt,name=PingerID" json:"PingerID,omitempty"`
}

func (m *PingListRequest) Reset()                    { *m = PingListRequest{} }
func (m *PingListRequest) String() string            { return proto.CompactTextString(m) }
func (*PingListRequest) ProtoMessage()               {}
func (*PingListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingListRequest) GetPingerID() string {
	if m != nil {
		return m.PingerID
	}
	return ""
}

type PingList struct {
	Entries []*PingEntry `protobuf:"bytes,1,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *PingList) Reset()                    { *m = PingList{} }
func (m *PingList) String() string            { return proto.CompactTextString(m) }
func (*PingList) ProtoMessage()               {}
func (*PingList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PingList) GetEntries() []*PingEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type PingEntry struct {
	ID             uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	IP             string `protobuf:"bytes,2,opt,name=IP" json:"IP,omitempty"`
	Interval       uint32 `protobuf:"varint,3,opt,name=Interval" json:"Interval,omitempty"`
	MetricHostName string `protobuf:"bytes,4,opt,name=MetricHostName" json:"MetricHostName,omitempty"`
	PingerID       string `protobuf:"bytes,5,opt,name=PingerID" json:"PingerID,omitempty"`
	Label          string `protobuf:"bytes,6,opt,name=Label" json:"Label,omitempty"`
	IPVersion      uint32 `protobuf:"varint,7,opt,name=IPVersion" json:"IPVersion,omitempty"`
	IsActive       bool   `protobuf:"varint,8,opt,name=IsActive" json:"IsActive,omitempty"`
	Label2         string `protobuf:"bytes,9,opt,name=Label2" json:"Label2,omitempty"`
	Label3         string `protobuf:"bytes,10,opt,name=Label3" json:"Label3,omitempty"`
	Label4         string `protobuf:"bytes,11,opt,name=Label4" json:"Label4,omitempty"`
}

func (m *PingEntry) Reset()                    { *m = PingEntry{} }
func (m *PingEntry) String() string            { return proto.CompactTextString(m) }
func (*PingEntry) ProtoMessage()               {}
func (*PingEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PingEntry) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PingEntry) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *PingEntry) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *PingEntry) GetMetricHostName() string {
	if m != nil {
		return m.MetricHostName
	}
	return ""
}

func (m *PingEntry) GetPingerID() string {
	if m != nil {
		return m.PingerID
	}
	return ""
}

func (m *PingEntry) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *PingEntry) GetIPVersion() uint32 {
	if m != nil {
		return m.IPVersion
	}
	return 0
}

func (m *PingEntry) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *PingEntry) GetLabel2() string {
	if m != nil {
		return m.Label2
	}
	return ""
}

func (m *PingEntry) GetLabel3() string {
	if m != nil {
		return m.Label3
	}
	return ""
}

func (m *PingEntry) GetLabel4() string {
	if m != nil {
		return m.Label4
	}
	return ""
}

type PingTargetStatus struct {
	IP        string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Reachable bool   `protobuf:"varint,3,opt,name=Reachable" json:"Reachable,omitempty"`
	Since     uint32 `protobuf:"varint,4,opt,name=Since" json:"Since,omitempty"`
}

func (m *PingTargetStatus) Reset()                    { *m = PingTargetStatus{} }
func (m *PingTargetStatus) String() string            { return proto.CompactTextString(m) }
func (*PingTargetStatus) ProtoMessage()               {}
func (*PingTargetStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PingTargetStatus) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *PingTargetStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PingTargetStatus) GetReachable() bool {
	if m != nil {
		return m.Reachable
	}
	return false
}

func (m *PingTargetStatus) GetSince() uint32 {
	if m != nil {
		return m.Since
	}
	return 0
}

type PingTargetStatusList struct {
	Status []*PingTargetStatus `protobuf:"bytes,1,rep,name=Status" json:"Status,omitempty"`
}

func (m *PingTargetStatusList) Reset()                    { *m = PingTargetStatusList{} }
func (m *PingTargetStatusList) String() string            { return proto.CompactTextString(m) }
func (*PingTargetStatusList) ProtoMessage()               {}
func (*PingTargetStatusList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PingTargetStatusList) GetStatus() []*PingTargetStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type SetPingStatusRequest struct {
	ID       uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Success  bool   `protobuf:"varint,2,opt,name=Success" json:"Success,omitempty"`
	PingerID string `protobuf:"bytes,3,opt,name=PingerID" json:"PingerID,omitempty"`
}

func (m *SetPingStatusRequest) Reset()                    { *m = SetPingStatusRequest{} }
func (m *SetPingStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPingStatusRequest) ProtoMessage()               {}
func (*SetPingStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetPingStatusRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SetPingStatusRequest) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SetPingStatusRequest) GetPingerID() string {
	if m != nil {
		return m.PingerID
	}
	return ""
}

type PingStatus struct {
	PingEntry   *PingEntry `protobuf:"bytes,1,opt,name=PingEntry" json:"PingEntry,omitempty"`
	Currently   bool       `protobuf:"varint,3,opt,name=Currently" json:"Currently,omitempty"`
	Since       uint32     `protobuf:"varint,4,opt,name=Since" json:"Since,omitempty"`
	LastOnline  uint32     `protobuf:"varint,5,opt,name=LastOnline" json:"LastOnline,omitempty"`
	LastOffline uint32     `protobuf:"varint,6,opt,name=LastOffline" json:"LastOffline,omitempty"`
}

func (m *PingStatus) Reset()                    { *m = PingStatus{} }
func (m *PingStatus) String() string            { return proto.CompactTextString(m) }
func (*PingStatus) ProtoMessage()               {}
func (*PingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PingStatus) GetPingEntry() *PingEntry {
	if m != nil {
		return m.PingEntry
	}
	return nil
}

func (m *PingStatus) GetCurrently() bool {
	if m != nil {
		return m.Currently
	}
	return false
}

func (m *PingStatus) GetSince() uint32 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *PingStatus) GetLastOnline() uint32 {
	if m != nil {
		return m.LastOnline
	}
	return 0
}

func (m *PingStatus) GetLastOffline() uint32 {
	if m != nil {
		return m.LastOffline
	}
	return 0
}

type PingStatusList struct {
	Status []*PingStatus `protobuf:"bytes,1,rep,name=Status" json:"Status,omitempty"`
}

func (m *PingStatusList) Reset()                    { *m = PingStatusList{} }
func (m *PingStatusList) String() string            { return proto.CompactTextString(m) }
func (*PingStatusList) ProtoMessage()               {}
func (*PingStatusList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PingStatusList) GetStatus() []*PingStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Tag struct {
	ID      uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	TagName string `protobuf:"bytes,2,opt,name=TagName" json:"TagName,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Tag) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Tag) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

// an IP address, attached to a host
type IP struct {
	ID        uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	IPVersion uint32 `protobuf:"varint,2,opt,name=IPVersion" json:"IPVersion,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	IP        string `protobuf:"bytes,4,opt,name=IP" json:"IP,omitempty"`
	Host      *Host  `protobuf:"bytes,5,opt,name=Host" json:"Host,omitempty"`
}

func (m *IP) Reset()                    { *m = IP{} }
func (m *IP) String() string            { return proto.CompactTextString(m) }
func (*IP) ProtoMessage()               {}
func (*IP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IP) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *IP) GetIPVersion() uint32 {
	if m != nil {
		return m.IPVersion
	}
	return 0
}

func (m *IP) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IP) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *IP) GetHost() *Host {
	if m != nil {
		return m.Host
	}
	return nil
}

// a host is just a name, but it might have multiple IPs
type Host struct {
	ID       uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	PingerID string `protobuf:"bytes,3,opt,name=PingerID" json:"PingerID,omitempty"`
}

func (m *Host) Reset()                    { *m = Host{} }
func (m *Host) String() string            { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()               {}
func (*Host) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Host) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetPingerID() string {
	if m != nil {
		return m.PingerID
	}
	return ""
}

// a uni-directional route from one ip to another
type Route struct {
	ID       uint64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	SourceIP *IP    `protobuf:"bytes,2,opt,name=SourceIP" json:"SourceIP,omitempty"`
	DestIP   *IP    `protobuf:"bytes,3,opt,name=DestIP" json:"DestIP,omitempty"`
}

func (m *Route) Reset()                    { *m = Route{} }
func (m *Route) String() string            { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()               {}
func (*Route) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Route) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Route) GetSourceIP() *IP {
	if m != nil {
		return m.SourceIP
	}
	return nil
}

func (m *Route) GetDestIP() *IP {
	if m != nil {
		return m.DestIP
	}
	return nil
}

// tags are attached to routes
type AddTagRequest struct {
	RouteID uint64 `protobuf:"varint,1,opt,name=RouteID" json:"RouteID,omitempty"`
	Tag     *Tag   `protobuf:"bytes,2,opt,name=Tag" json:"Tag,omitempty"`
}

func (m *AddTagRequest) Reset()                    { *m = AddTagRequest{} }
func (m *AddTagRequest) String() string            { return proto.CompactTextString(m) }
func (*AddTagRequest) ProtoMessage()               {}
func (*AddTagRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AddTagRequest) GetRouteID() uint64 {
	if m != nil {
		return m.RouteID
	}
	return 0
}

func (m *AddTagRequest) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type RemoveTagRequest struct {
	RouteID uint64 `protobuf:"varint,1,opt,name=RouteID" json:"RouteID,omitempty"`
	TagID   uint64 `protobuf:"varint,2,opt,name=TagID" json:"TagID,omitempty"`
}

func (m *RemoveTagRequest) Reset()                    { *m = RemoveTagRequest{} }
func (m *RemoveTagRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveTagRequest) ProtoMessage()               {}
func (*RemoveTagRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RemoveTagRequest) GetRouteID() uint64 {
	if m != nil {
		return m.RouteID
	}
	return 0
}

func (m *RemoveTagRequest) GetTagID() uint64 {
	if m != nil {
		return m.TagID
	}
	return 0
}

type TagList struct {
	Tags []*Tag `protobuf:"bytes,1,rep,name=Tags" json:"Tags,omitempty"`
}

func (m *TagList) Reset()                    { *m = TagList{} }
func (m *TagList) String() string            { return proto.CompactTextString(m) }
func (*TagList) ProtoMessage()               {}
func (*TagList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *TagList) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AddIPRequest struct {
	HostID    uint64 `protobuf:"varint,1,opt,name=HostID" json:"HostID,omitempty"`
	IP        string `protobuf:"bytes,2,opt,name=IP" json:"IP,omitempty"`
	IPVersion uint32 `protobuf:"varint,3,opt,name=IPVersion" json:"IPVersion,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
}

func (m *AddIPRequest) Reset()                    { *m = AddIPRequest{} }
func (m *AddIPRequest) String() string            { return proto.CompactTextString(m) }
func (*AddIPRequest) ProtoMessage()               {}
func (*AddIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AddIPRequest) GetHostID() uint64 {
	if m != nil {
		return m.HostID
	}
	return 0
}

func (m *AddIPRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *AddIPRequest) GetIPVersion() uint32 {
	if m != nil {
		return m.IPVersion
	}
	return 0
}

func (m *AddIPRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StatusMatrixList struct {
	Matrices []*StatusMatrix `protobuf:"bytes,1,rep,name=Matrices" json:"Matrices,omitempty"`
}

func (m *StatusMatrixList) Reset()                    { *m = StatusMatrixList{} }
func (m *StatusMatrixList) String() string            { return proto.CompactTextString(m) }
func (*StatusMatrixList) ProtoMessage()               {}
func (*StatusMatrixList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *StatusMatrixList) GetMatrices() []*StatusMatrix {
	if m != nil {
		return m.Matrices
	}
	return nil
}

type StatusMatrix struct {
	Name           string                 `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Failed         uint32                 `protobuf:"varint,2,opt,name=Failed" json:"Failed,omitempty"`
	Working        uint32                 `protobuf:"varint,3,opt,name=Working" json:"Working,omitempty"`
	Rows           []*MatrixRow           `protobuf:"bytes,4,rep,name=Rows" json:"Rows,omitempty"`
	ColumnHeadings []*MatrixColumnHeading `protobuf:"bytes,5,rep,name=ColumnHeadings" json:"ColumnHeadings,omitempty"`
}

func (m *StatusMatrix) Reset()                    { *m = StatusMatrix{} }
func (m *StatusMatrix) String() string            { return proto.CompactTextString(m) }
func (*StatusMatrix) ProtoMessage()               {}
func (*StatusMatrix) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *StatusMatrix) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatusMatrix) GetFailed() uint32 {
	if m != nil {
		return m.Failed
	}
	return 0
}

func (m *StatusMatrix) GetWorking() uint32 {
	if m != nil {
		return m.Working
	}
	return 0
}

func (m *StatusMatrix) GetRows() []*MatrixRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *StatusMatrix) GetColumnHeadings() []*MatrixColumnHeading {
	if m != nil {
		return m.ColumnHeadings
	}
	return nil
}

type MatrixColumnHeading struct {
	DisplayName string `protobuf:"bytes,1,opt,name=DisplayName" json:"DisplayName,omitempty"`
}

func (m *MatrixColumnHeading) Reset()                    { *m = MatrixColumnHeading{} }
func (m *MatrixColumnHeading) String() string            { return proto.CompactTextString(m) }
func (*MatrixColumnHeading) ProtoMessage()               {}
func (*MatrixColumnHeading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MatrixColumnHeading) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type MatrixRow struct {
	Hostname string         `protobuf:"bytes,1,opt,name=Hostname" json:"Hostname,omitempty"`
	IP       string         `protobuf:"bytes,2,opt,name=IP" json:"IP,omitempty"`
	Entries  []*MatrixEntry `protobuf:"bytes,3,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *MatrixRow) Reset()                    { *m = MatrixRow{} }
func (m *MatrixRow) String() string            { return proto.CompactTextString(m) }
func (*MatrixRow) ProtoMessage()               {}
func (*MatrixRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *MatrixRow) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *MatrixRow) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *MatrixRow) GetEntries() []*MatrixEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type MatrixEntry struct {
	Reachable     bool   `protobuf:"varint,1,opt,name=Reachable" json:"Reachable,omitempty"`
	Tested        bool   `protobuf:"varint,2,opt,name=Tested" json:"Tested,omitempty"`
	DisplayName   string `protobuf:"bytes,3,opt,name=DisplayName" json:"DisplayName,omitempty"`
	DisplayColour string `protobuf:"bytes,4,opt,name=DisplayColour" json:"DisplayColour,omitempty"`
}

func (m *MatrixEntry) Reset()                    { *m = MatrixEntry{} }
func (m *MatrixEntry) String() string            { return proto.CompactTextString(m) }
func (*MatrixEntry) ProtoMessage()               {}
func (*MatrixEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *MatrixEntry) GetReachable() bool {
	if m != nil {
		return m.Reachable
	}
	return false
}

func (m *MatrixEntry) GetTested() bool {
	if m != nil {
		return m.Tested
	}
	return false
}

func (m *MatrixEntry) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *MatrixEntry) GetDisplayColour() string {
	if m != nil {
		return m.DisplayColour
	}
	return ""
}

func init() {
	proto.RegisterType((*PingResult)(nil), "pinger.PingResult")
	proto.RegisterType((*PingRequest)(nil), "pinger.PingRequest")
	proto.RegisterType((*PingListRequest)(nil), "pinger.PingListRequest")
	proto.RegisterType((*PingList)(nil), "pinger.PingList")
	proto.RegisterType((*PingEntry)(nil), "pinger.PingEntry")
	proto.RegisterType((*PingTargetStatus)(nil), "pinger.PingTargetStatus")
	proto.RegisterType((*PingTargetStatusList)(nil), "pinger.PingTargetStatusList")
	proto.RegisterType((*SetPingStatusRequest)(nil), "pinger.SetPingStatusRequest")
	proto.RegisterType((*PingStatus)(nil), "pinger.PingStatus")
	proto.RegisterType((*PingStatusList)(nil), "pinger.PingStatusList")
	proto.RegisterType((*Tag)(nil), "pinger.Tag")
	proto.RegisterType((*IP)(nil), "pinger.IP")
	proto.RegisterType((*Host)(nil), "pinger.Host")
	proto.RegisterType((*Route)(nil), "pinger.Route")
	proto.RegisterType((*AddTagRequest)(nil), "pinger.AddTagRequest")
	proto.RegisterType((*RemoveTagRequest)(nil), "pinger.RemoveTagRequest")
	proto.RegisterType((*TagList)(nil), "pinger.TagList")
	proto.RegisterType((*AddIPRequest)(nil), "pinger.AddIPRequest")
	proto.RegisterType((*StatusMatrixList)(nil), "pinger.StatusMatrixList")
	proto.RegisterType((*StatusMatrix)(nil), "pinger.StatusMatrix")
	proto.RegisterType((*MatrixColumnHeading)(nil), "pinger.MatrixColumnHeading")
	proto.RegisterType((*MatrixRow)(nil), "pinger.MatrixRow")
	proto.RegisterType((*MatrixEntry)(nil), "pinger.MatrixEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Pinger service

type PingerClient interface {
	// execute a single ping
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResult, error)
	// get list of current ping targets and their status
	PingStatus(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*PingTargetStatusList, error)
}

type pingerClient struct {
	cc *grpc.ClientConn
}

func NewPingerClient(cc *grpc.ClientConn) PingerClient {
	return &pingerClient{cc}
}

func (c *pingerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResult, error) {
	out := new(PingResult)
	err := grpc.Invoke(ctx, "/pinger.Pinger/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerClient) PingStatus(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*PingTargetStatusList, error) {
	out := new(PingTargetStatusList)
	err := grpc.Invoke(ctx, "/pinger.Pinger/PingStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pinger service

type PingerServer interface {
	// execute a single ping
	Ping(context.Context, *PingRequest) (*PingResult, error)
	// get list of current ping targets and their status
	PingStatus(context.Context, *common.Void) (*PingTargetStatusList, error)
}

func RegisterPingerServer(s *grpc.Server, srv PingerServer) {
	s.RegisterService(&_Pinger_serviceDesc, srv)
}

func _Pinger_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.Pinger/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pinger_PingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).PingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.Pinger/PingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).PingStatus(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pinger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pinger.Pinger",
	HandlerType: (*PingerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Pinger_Ping_Handler,
		},
		{
			MethodName: "PingStatus",
			Handler:    _Pinger_PingStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "golang.conradwood.net/apis/pinger/pinger.proto",
}

// Client API for PingerList service

type PingerListClient interface {
	// get ping config (list of ip addresses to ping regularly).
	GetPingList(ctx context.Context, in *PingListRequest, opts ...grpc.CallOption) (*PingList, error)
	// pinger reports a status through this RPC
	SetPingStatus(ctx context.Context, in *SetPingStatusRequest, opts ...grpc.CallOption) (*common.Void, error)
	// get a list of all known status'
	GetPingStatus(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*PingStatusList, error)
	// create a host
	CreateHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Host, error)
	// add an ip to host
	AddIP(ctx context.Context, in *AddIPRequest, opts ...grpc.CallOption) (*IP, error)
	// create a route that is to be checked (from one ip to another)
	CreateRoute(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Route, error)
	// add tag to host
	AddTag(ctx context.Context, in *AddTagRequest, opts ...grpc.CallOption) (*TagList, error)
	// remove tag from host
	RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*TagList, error)
	// get status matrix
	GetStatusMatrix(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*StatusMatrixList, error)
}

type pingerListClient struct {
	cc *grpc.ClientConn
}

func NewPingerListClient(cc *grpc.ClientConn) PingerListClient {
	return &pingerListClient{cc}
}

func (c *pingerListClient) GetPingList(ctx context.Context, in *PingListRequest, opts ...grpc.CallOption) (*PingList, error) {
	out := new(PingList)
	err := grpc.Invoke(ctx, "/pinger.PingerList/GetPingList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) SetPingStatus(ctx context.Context, in *SetPingStatusRequest, opts ...grpc.CallOption) (*common.Void, error) {
	out := new(common.Void)
	err := grpc.Invoke(ctx, "/pinger.PingerList/SetPingStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) GetPingStatus(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*PingStatusList, error) {
	out := new(PingStatusList)
	err := grpc.Invoke(ctx, "/pinger.PingerList/GetPingStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) CreateHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Host, error) {
	out := new(Host)
	err := grpc.Invoke(ctx, "/pinger.PingerList/CreateHost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) AddIP(ctx context.Context, in *AddIPRequest, opts ...grpc.CallOption) (*IP, error) {
	out := new(IP)
	err := grpc.Invoke(ctx, "/pinger.PingerList/AddIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) CreateRoute(ctx context.Context, in *Route, opts ...grpc.CallOption) (*Route, error) {
	out := new(Route)
	err := grpc.Invoke(ctx, "/pinger.PingerList/CreateRoute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) AddTag(ctx context.Context, in *AddTagRequest, opts ...grpc.CallOption) (*TagList, error) {
	out := new(TagList)
	err := grpc.Invoke(ctx, "/pinger.PingerList/AddTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) RemoveTag(ctx context.Context, in *RemoveTagRequest, opts ...grpc.CallOption) (*TagList, error) {
	out := new(TagList)
	err := grpc.Invoke(ctx, "/pinger.PingerList/RemoveTag", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerListClient) GetStatusMatrix(ctx context.Context, in *common.Void, opts ...grpc.CallOption) (*StatusMatrixList, error) {
	out := new(StatusMatrixList)
	err := grpc.Invoke(ctx, "/pinger.PingerList/GetStatusMatrix", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PingerList service

type PingerListServer interface {
	// get ping config (list of ip addresses to ping regularly).
	GetPingList(context.Context, *PingListRequest) (*PingList, error)
	// pinger reports a status through this RPC
	SetPingStatus(context.Context, *SetPingStatusRequest) (*common.Void, error)
	// get a list of all known status'
	GetPingStatus(context.Context, *common.Void) (*PingStatusList, error)
	// create a host
	CreateHost(context.Context, *Host) (*Host, error)
	// add an ip to host
	AddIP(context.Context, *AddIPRequest) (*IP, error)
	// create a route that is to be checked (from one ip to another)
	CreateRoute(context.Context, *Route) (*Route, error)
	// add tag to host
	AddTag(context.Context, *AddTagRequest) (*TagList, error)
	// remove tag from host
	RemoveTag(context.Context, *RemoveTagRequest) (*TagList, error)
	// get status matrix
	GetStatusMatrix(context.Context, *common.Void) (*StatusMatrixList, error)
}

func RegisterPingerListServer(s *grpc.Server, srv PingerListServer) {
	s.RegisterService(&_PingerList_serviceDesc, srv)
}

func _PingerList_GetPingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).GetPingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/GetPingList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).GetPingList(ctx, req.(*PingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_SetPingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPingStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).SetPingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/SetPingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).SetPingStatus(ctx, req.(*SetPingStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_GetPingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).GetPingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/GetPingStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).GetPingStatus(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_CreateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).CreateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/CreateHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).CreateHost(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_AddIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).AddIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/AddIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).AddIP(ctx, req.(*AddIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Route)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/CreateRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).CreateRoute(ctx, req.(*Route))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_AddTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).AddTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/AddTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).AddTag(ctx, req.(*AddTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_RemoveTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).RemoveTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/RemoveTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).RemoveTag(ctx, req.(*RemoveTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingerList_GetStatusMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerListServer).GetStatusMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pinger.PingerList/GetStatusMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerListServer).GetStatusMatrix(ctx, req.(*common.Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingerList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pinger.PingerList",
	HandlerType: (*PingerListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPingList",
			Handler:    _PingerList_GetPingList_Handler,
		},
		{
			MethodName: "SetPingStatus",
			Handler:    _PingerList_SetPingStatus_Handler,
		},
		{
			MethodName: "GetPingStatus",
			Handler:    _PingerList_GetPingStatus_Handler,
		},
		{
			MethodName: "CreateHost",
			Handler:    _PingerList_CreateHost_Handler,
		},
		{
			MethodName: "AddIP",
			Handler:    _PingerList_AddIP_Handler,
		},
		{
			MethodName: "CreateRoute",
			Handler:    _PingerList_CreateRoute_Handler,
		},
		{
			MethodName: "AddTag",
			Handler:    _PingerList_AddTag_Handler,
		},
		{
			MethodName: "RemoveTag",
			Handler:    _PingerList_RemoveTag_Handler,
		},
		{
			MethodName: "GetStatusMatrix",
			Handler:    _PingerList_GetStatusMatrix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "golang.conradwood.net/apis/pinger/pinger.proto",
}

func init() { proto.RegisterFile("golang.conradwood.net/apis/pinger/pinger.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x56, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0x96, 0x73, 0x71, 0x93, 0x93, 0xa6, 0x2d, 0xd3, 0x6e, 0xf1, 0x9a, 0x2e, 0x14, 0x0b, 0x50,
	0xd9, 0xd5, 0xa6, 0x28, 0x2d, 0xdb, 0x45, 0x8b, 0x84, 0xda, 0x86, 0x6d, 0x23, 0xb5, 0x10, 0xb9,
	0xd1, 0x22, 0xad, 0x78, 0x71, 0xed, 0xa9, 0x6b, 0x70, 0x3d, 0xc5, 0x9e, 0xb4, 0xf4, 0x75, 0x5f,
	0x11, 0xe2, 0x9d, 0x47, 0xf8, 0x09, 0xfc, 0x01, 0xfe, 0x0a, 0xff, 0x04, 0xcd, 0xc5, 0x93, 0x19,
	0x27, 0x7b, 0x79, 0x4a, 0xbe, 0x73, 0x99, 0x39, 0x97, 0xcf, 0xe7, 0x0c, 0xf4, 0x62, 0x92, 0x06,
	0x59, 0xdc, 0x0b, 0x49, 0x96, 0x07, 0xd1, 0x2d, 0x21, 0x51, 0x2f, 0xc3, 0x74, 0x3b, 0xb8, 0x4e,
	0x8a, 0xed, 0xeb, 0x24, 0x8b, 0x71, 0x2e, 0x7f, 0x7a, 0xd7, 0x39, 0xa1, 0x04, 0xd9, 0x02, 0xb9,
	0x6f, 0xf2, 0x0b, 0xc9, 0xd5, 0x15, 0xc9, 0xe4, 0x8f, 0xf0, 0xf3, 0x5e, 0x02, 0x8c, 0x92, 0x2c,
	0xf6, 0x71, 0x31, 0x49, 0x29, 0x5a, 0x82, 0xda, 0x70, 0xe4, 0x58, 0x9b, 0xd6, 0x56, 0xdb, 0xaf,
	0x0d, 0x47, 0xc8, 0x83, 0xc5, 0xd3, 0x24, 0x4d, 0x93, 0x02, 0x87, 0x24, 0x8b, 0x0a, 0xa7, 0xb6,
	0x69, 0x6d, 0x75, 0x7d, 0x43, 0x86, 0x1c, 0x58, 0x38, 0x9b, 0x84, 0x21, 0x2e, 0x0a, 0xa7, 0xbe,
	0x69, 0x6d, 0xb5, 0xfc, 0x12, 0x7a, 0x0f, 0xa0, 0x23, 0xce, 0xfe, 0x65, 0x82, 0x8b, 0x99, 0xc3,
	0xbd, 0xc7, 0xb0, 0xcc, 0xd4, 0x27, 0x49, 0x41, 0x4b, 0x13, 0x17, 0x5a, 0x23, 0x9e, 0xc7, 0x70,
	0x20, 0x0d, 0x15, 0xf6, 0xf6, 0x84, 0x8e, 0x99, 0xa3, 0x47, 0xb0, 0xf0, 0x6d, 0x46, 0xf3, 0x04,
	0x17, 0x8e, 0xb5, 0x59, 0xdf, 0xea, 0xf4, 0xdf, 0xeb, 0xc9, 0x6a, 0x30, 0x13, 0xa6, 0xba, 0xf3,
	0x4b, 0x0b, 0xef, 0xef, 0x1a, 0xb4, 0x95, 0x98, 0x47, 0x21, 0x0e, 0x6f, 0xf8, 0xb5, 0xe1, 0x40,
	0x46, 0x55, 0x53, 0x29, 0xbb, 0xd0, 0x1a, 0x66, 0x14, 0xe7, 0x37, 0x41, 0xca, 0xf3, 0xe9, 0xfa,
	0x0a, 0xa3, 0xcf, 0x60, 0xe9, 0x14, 0xd3, 0x3c, 0x09, 0x8f, 0x49, 0x41, 0xbf, 0x0b, 0xae, 0xb0,
	0xd3, 0xe0, 0x7e, 0x15, 0xa9, 0x91, 0x46, 0xd3, 0x4c, 0x03, 0xad, 0x41, 0xf3, 0x24, 0x38, 0xc7,
	0xa9, 0x63, 0x73, 0x85, 0x00, 0x68, 0x03, 0xda, 0xc3, 0xd1, 0x0b, 0x9c, 0x17, 0x09, 0xc9, 0x9c,
	0x05, 0x7e, 0xed, 0x54, 0xc0, 0x63, 0x2a, 0xf6, 0x43, 0x9a, 0xdc, 0x60, 0xa7, 0xc5, 0x6b, 0xac,
	0x30, 0x5a, 0x07, 0x9b, 0x1f, 0xd1, 0x77, 0xda, 0xfc, 0x40, 0x89, 0x94, 0x7c, 0xc7, 0x01, 0x4d,
	0xbe, 0xa3, 0xe4, 0xbb, 0x4e, 0x47, 0x93, 0xef, 0x7a, 0x3f, 0xc1, 0x0a, 0x8b, 0x71, 0x1c, 0xe4,
	0x31, 0xa6, 0x67, 0x34, 0xa0, 0x93, 0x62, 0x86, 0x0e, 0x08, 0x1a, 0x3c, 0x6b, 0x51, 0x2d, 0xfe,
	0x9f, 0x45, 0xee, 0xe3, 0x20, 0xbc, 0x0c, 0xce, 0x53, 0x2c, 0x09, 0x30, 0x15, 0xb0, 0x6c, 0xcf,
	0x92, 0x2c, 0x14, 0x85, 0xea, 0xfa, 0x02, 0x78, 0xc7, 0xb0, 0x56, 0xbd, 0x8b, 0xb7, 0xf5, 0x0b,
	0xb0, 0x05, 0x92, 0x5d, 0x75, 0xf4, 0xae, 0xea, 0xd6, 0xbe, 0xb4, 0xf3, 0x7e, 0x84, 0xb5, 0x33,
	0x4c, 0x99, 0x5a, 0x2a, 0x34, 0xae, 0xe9, 0x5d, 0xd6, 0x48, 0x5a, 0x33, 0x48, 0x6a, 0xf4, 0xaa,
	0x5e, 0xa1, 0xdc, 0x3f, 0x96, 0xf8, 0x3a, 0x64, 0x39, 0xb6, 0x35, 0x1e, 0xf1, 0xb3, 0xe7, 0xf2,
	0x4e, 0xe3, 0xda, 0x06, 0xb4, 0x0f, 0x27, 0x79, 0x8e, 0x33, 0x9a, 0xde, 0x95, 0xb5, 0x51, 0x82,
	0xf9, 0xb5, 0x41, 0x1f, 0x02, 0x9c, 0x04, 0x05, 0xfd, 0x3e, 0x4b, 0x93, 0x0c, 0x73, 0xf6, 0x74,
	0x7d, 0x4d, 0x82, 0x36, 0xa1, 0xc3, 0xd1, 0xc5, 0x05, 0x37, 0xb0, 0xb9, 0x81, 0x2e, 0xf2, 0xbe,
	0x86, 0xa5, 0x69, 0xd0, 0xbc, 0xae, 0x0f, 0x2b, 0x75, 0x45, 0x7a, 0xd4, 0x95, 0x8a, 0x6e, 0x43,
	0x7d, 0x1c, 0xc4, 0xf3, 0x0a, 0x38, 0x0e, 0x62, 0xad, 0xfb, 0x25, 0xf4, 0xfe, 0xb0, 0x18, 0x4b,
	0x66, 0x1c, 0x0c, 0x46, 0xd7, 0xaa, 0x8c, 0x2e, 0x99, 0x54, 0xd7, 0x98, 0x24, 0xd8, 0xd6, 0x50,
	0x6c, 0xdb, 0x83, 0x06, 0xfb, 0xa2, 0x78, 0x0d, 0x3a, 0xfd, 0xc5, 0x32, 0x66, 0x26, 0x3b, 0xb8,
	0xf7, 0xe7, 0xab, 0xfb, 0xf6, 0x24, 0xc9, 0xe8, 0x93, 0xdd, 0xbf, 0x5e, 0xdd, 0x5f, 0xb8, 0x24,
	0x05, 0xed, 0x25, 0x91, 0xcf, 0x1d, 0xbc, 0xe7, 0xc2, 0x71, 0x26, 0xa4, 0x79, 0xf4, 0x7d, 0x53,
	0xfb, 0x7f, 0xb7, 0xa0, 0xe9, 0x93, 0x09, 0xc5, 0x33, 0x27, 0x3d, 0x83, 0xd6, 0x19, 0x99, 0xe4,
	0x21, 0x96, 0xa3, 0xa3, 0xd3, 0x87, 0x32, 0xbc, 0xe1, 0xe8, 0x60, 0xd5, 0x08, 0xae, 0x99, 0x5c,
	0xb3, 0xd0, 0x94, 0x03, 0xda, 0x03, 0x7b, 0x80, 0x0b, 0x3a, 0x1c, 0xf1, 0x0b, 0xdf, 0xc1, 0x55,
	0x9a, 0x7b, 0xc7, 0xd0, 0xdd, 0x8f, 0xa2, 0x71, 0xa0, 0x26, 0xaa, 0x03, 0x0b, 0x3c, 0x3e, 0x15,
	0x5b, 0x09, 0xd1, 0x03, 0xde, 0x45, 0x19, 0x5b, 0xa7, 0xbc, 0x80, 0xb9, 0x32, 0xb9, 0x77, 0x00,
	0x2b, 0x3e, 0xbe, 0x22, 0x37, 0xf8, 0x9d, 0x0e, 0x5b, 0x83, 0xe6, 0x38, 0x88, 0x87, 0x03, 0x7e,
	0x5c, 0xc3, 0x17, 0xc0, 0x7b, 0xc8, 0x19, 0xc1, 0xf9, 0xf5, 0x11, 0x34, 0xc6, 0x41, 0x5c, 0xb2,
	0xcb, 0xb8, 0x8e, 0x2b, 0xbc, 0x4b, 0x58, 0xdc, 0x8f, 0xa2, 0xe1, 0xa8, 0xbc, 0x6b, 0x1d, 0x6c,
	0xd6, 0x21, 0x75, 0x95, 0x44, 0x33, 0xc3, 0xd8, 0x20, 0x51, 0xfd, 0x75, 0x24, 0x6a, 0x4c, 0xfb,
	0xe9, 0x0d, 0x60, 0x45, 0x10, 0xf9, 0x34, 0xa0, 0x79, 0xf2, 0xab, 0x1c, 0x2b, 0x2d, 0x8e, 0x42,
	0xb5, 0x2e, 0xd6, 0xca, 0x10, 0x75, 0x5b, 0x5f, 0x59, 0x79, 0xff, 0x5a, 0xb0, 0xa8, 0xab, 0xd4,
	0x55, 0x96, 0x46, 0x9d, 0x75, 0xb0, 0x9f, 0x07, 0x49, 0x8a, 0x23, 0x49, 0x6f, 0x89, 0x58, 0x21,
	0x7f, 0x20, 0xf9, 0xcf, 0x49, 0x16, 0xcb, 0x90, 0x4b, 0x88, 0x3e, 0x85, 0x86, 0x4f, 0x6e, 0x0b,
	0xa7, 0x61, 0xee, 0x2c, 0x79, 0x3d, 0xb9, 0xf5, 0xb9, 0x1a, 0x1d, 0xc2, 0xd2, 0x21, 0x49, 0x27,
	0x57, 0xd9, 0x31, 0x0e, 0xa2, 0x24, 0x8b, 0x0b, 0xa7, 0xc9, 0x1d, 0x3e, 0x30, 0x1d, 0x0c, 0x1b,
	0xbf, 0xe2, 0xe2, 0xed, 0xc1, 0xea, 0x1c, 0x33, 0x36, 0x3e, 0x06, 0x49, 0x71, 0x9d, 0x06, 0x77,
	0x5a, 0x3e, 0xba, 0xc8, 0xbb, 0x80, 0xb6, 0x0a, 0x88, 0x7d, 0x1e, 0xac, 0x35, 0xd9, 0xd4, 0x56,
	0xe1, 0x99, 0x66, 0x3d, 0x9e, 0x2e, 0xe5, 0x3a, 0x8f, 0x77, 0xd5, 0x8c, 0xb7, 0xb2, 0x96, 0x7f,
	0xb3, 0xa0, 0xa3, 0x29, 0xcc, 0x45, 0x62, 0x55, 0x17, 0xc9, 0x3a, 0xd8, 0x63, 0x5c, 0x50, 0x59,
	0xec, 0x96, 0x2f, 0x51, 0x35, 0x9f, 0xfa, 0x4c, 0x3e, 0xe8, 0x13, 0xe8, 0x4a, 0x78, 0x48, 0x52,
	0x32, 0xc9, 0x25, 0x5d, 0x4c, 0x61, 0xbf, 0x00, 0x5b, 0x7c, 0xf7, 0x68, 0x1b, 0x1a, 0xec, 0x1f,
	0x5a, 0xd5, 0x87, 0xa4, 0x24, 0xae, 0x8b, 0x4c, 0x21, 0x7f, 0x34, 0x3d, 0x35, 0x96, 0xc4, 0x62,
	0x4f, 0xbe, 0xaf, 0x5e, 0x90, 0x24, 0x72, 0x37, 0x5e, 0xb7, 0xc1, 0x18, 0x31, 0xfb, 0xff, 0xd5,
	0x85, 0x2b, 0xce, 0x39, 0x4f, 0x9f, 0x42, 0xe7, 0x48, 0x2c, 0x33, 0x0e, 0xdf, 0xd7, 0x7d, 0xb5,
	0x57, 0x92, 0xbb, 0x52, 0x55, 0xa0, 0x67, 0xd0, 0x35, 0xd6, 0x20, 0x52, 0xf7, 0xce, 0xdb, 0x8e,
	0xae, 0x11, 0x23, 0xfa, 0x12, 0xba, 0x47, 0x86, 0xb3, 0x99, 0xc2, 0xfa, 0xec, 0xb2, 0xe0, 0x77,
	0x6e, 0x01, 0x1c, 0xe6, 0x38, 0xa0, 0x98, 0xcf, 0x5a, 0x63, 0x3c, 0xbb, 0x06, 0x42, 0x9f, 0x43,
	0x93, 0x7f, 0xfd, 0x48, 0x7d, 0x76, 0xfa, 0x30, 0x70, 0xb5, 0xf9, 0x87, 0x1e, 0x41, 0x47, 0x1c,
	0x2a, 0xe6, 0x6e, 0xb7, 0x54, 0x71, 0xe8, 0x9a, 0x90, 0x3d, 0x17, 0xc4, 0x3c, 0x44, 0xf7, 0xb4,
	0x83, 0xa7, 0x23, 0xcd, 0x5d, 0xd6, 0x26, 0x11, 0x8f, 0xf9, 0x09, 0xe3, 0x98, 0x9c, 0x7b, 0x48,
	0xbd, 0x2e, 0xaa, 0xa3, 0x70, 0xd6, 0xef, 0x2b, 0x58, 0x3e, 0x2a, 0x3b, 0x27, 0x27, 0x82, 0x59,
	0x24, 0x67, 0xde, 0x40, 0x61, 0xae, 0x07, 0xdf, 0x80, 0x9b, 0x61, 0xaa, 0xbf, 0xc7, 0xd9, 0x5b,
	0x5c, 0x9a, 0xbf, 0xfc, 0xf8, 0xad, 0xcf, 0xfc, 0x73, 0x9b, 0x3f, 0xd4, 0x77, 0xfe, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0xdd, 0x0e, 0x17, 0x84, 0x12, 0x0c, 0x00, 0x00,
}
